# Generated by Django 4.2.16 on 2024-11-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(max_length=60)),
            ],
        ),
    ]
