# Generated by Django 4.2.16 on 2024-11-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellany', '0004_alter_presence_presence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenceitem',
            name='is_present',
        ),
    ]
