# Generated by Django 4.2.16 on 2024-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_account_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
